User.create!([
  {email: "exam@gmail.com", encrypted_password: "$2a$10$lOJ/3cvGyLFSF5GVj3Fhwel/d88o0WdThXtFnA.H7kTJ2JM2s6rNm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 18, current_sign_in_at: "2015-06-08 08:34:07", last_sign_in_at: "2015-06-08 08:28:21", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "Admin"},
  {email: "student@gmail.com", encrypted_password: "$2a$10$9qKExTplMsmB6C63uPnvQOrj3OwMO9PgVNq69LCUHk9.N05kVbYF2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 32, current_sign_in_at: "2015-06-08 08:45:48", last_sign_in_at: "2015-06-08 08:34:31", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "Student"}
])
Answer.create!([
  {question_id: 43, content: "a"},
  {question_id: 43, content: "A"},
  {question_id: 43, content: "c"},
  {question_id: 43, content: "65"},
  {question_id: 44, content: "True "},
  {question_id: 44, content: "false"},
  {question_id: 44, content: "Error"},
  {question_id: 44, content: "None of Above"},
  {question_id: 45, content: "Infinite loop"},
  {question_id: 45, content: "0 1 2 ... 65535"},
  {question_id: 45, content: "0 1 2 ... 32767 - 32766 -32765 -1 0"},
  {question_id: 45, content: "\t No output"},
  {question_id: 46, content: "4"},
  {question_id: 46, content: "8"},
  {question_id: 46, content: "16"},
  {question_id: 46, content: "22"},
  {question_id: 47, content: "ffff"},
  {question_id: 47, content: "0000"},
  {question_id: 47, content: "00ff"},
  {question_id: 47, content: "ddfd"},
  {question_id: 48, content: "Oxygen"},
  {question_id: 48, content: "Hydrogen sulphide"},
  {question_id: 48, content: "Carbon dioxide"},
  {question_id: 48, content: "Nitrogen"},
  {question_id: 49, content: "Phosphorous"},
  {question_id: 49, content: "Bromine"},
  {question_id: 49, content: "Chlorine"},
  {question_id: 49, content: "Helium"},
  {question_id: 50, content: "copper"},
  {question_id: 50, content: "magnesium"},
  {question_id: 50, content: "iron"},
  {question_id: 50, content: "calcium"},
  {question_id: 51, content: "Graphite"},
  {question_id: 51, content: "Silicon"},
  {question_id: 51, content: "Charcoal"},
  {question_id: 51, content: "Phosphorous"},
  {question_id: 52, content: "Tin"},
  {question_id: 52, content: "Mercury"},
  {question_id: 52, content: "Lead"},
  {question_id: 52, content: "Charcoal"},
  {question_id: 93, content: "Red"},
  {question_id: 93, content: "Orange"},
  {question_id: 93, content: "pink"},
  {question_id: 93, content: "yellow"},
  {question_id: 94, content: "4"},
  {question_id: 94, content: "60"},
  {question_id: 94, content: "15"},
  {question_id: 94, content: "0.25"},
  {question_id: 95, content: "neutros-p"},
  {question_id: 95, content: "protons"},
  {question_id: 95, content: "electrons"},
  {question_id: 95, content: "neutrons"},
  {question_id: 96, content: "open"},
  {question_id: 96, content: "insulated"},
  {question_id: 96, content: "high resistance"},
  {question_id: 96, content: "closed"},
  {question_id: 97, content: "Thermistor"},
  {question_id: 97, content: "Rheostat"},
  {question_id: 97, content: "Potentiometer"},
  {question_id: 97, content: "Photoconductive cell"},
  {question_id: 98, content: "largest railway station"},
  {question_id: 98, content: "highest railway station"},
  {question_id: 98, content: "longest railway station"},
  {question_id: 98, content: "None of the above"},
  {question_id: 99, content: "Behavior of human beings"},
  {question_id: 99, content: "Insects"},
  {question_id: 99, content: "The origin and history of technical and scientific terms"},
  {question_id: 99, content: "The formation of rocks"},
  {question_id: 100, content: "Asia"},
  {question_id: 100, content: "Africa"},
  {question_id: 100, content: "Europe"},
  {question_id: 100, content: "Australia"},
  {question_id: 101, content: "Junagarh, Gujarat"},
  {question_id: 101, content: "Diphu, Assam"},
  {question_id: 101, content: "Kohima, Nagaland"},
  {question_id: 101, content: "Gangtok, Sikkim"},
  {question_id: 102, content: "Labour Party"},
  {question_id: 102, content: "Nazi Party"},
  {question_id: 102, content: "Ku-Klux-Klan"},
  {question_id: 102, content: "Democratic Party"}
])
Exam.create!([
  {name: "Programming"},
  {name: "Science"},
  {name: "Electronics"},
  {name: "General Knowledge"}
])
Question.create!([
  {exam_id: 9, content: "What will be the output of the program ?\r\n\r\n#include<stdio.h>\r\n\r\nint main()\r\n{\r\n    char p[] = \"%d\\n\";\r\n    p[1] = 'c';\r\n    printf(p, 65);\r\n    return 0;\r\n}", correct_answer: "A"},
  {exam_id: 9, content: "Once preprocessing is over and the program is sent for the compilation the macros are removed from the expanded source code.", correct_answer: "True"},
  {exam_id: 9, content: "What will be the output of the program?\r\n\r\n#include<stdio.h>\r\nint main()\r\n{\r\n    unsigned int i = 65535; /* Assume 2 byte integer*/\r\n    while(i++ != 0)\r\n        printf(\"%d\",++i);\r\n    printf(\"\\n\");\r\n    return 0;\r\n}", correct_answer: "Infinite loop"},
  {exam_id: 9, content: "What will be the output of the program in DOS (Compiler - Turbo C)?\r\n\r\n#include<stdio.h>\r\ndouble i;\r\n\r\nint main()\r\n{\r\n    (int)(float)(char) i;\r\n    printf(\"%d\",sizeof(i));\r\n    return 0;\r\n}", correct_answer: "4"},
  {exam_id: 9, content: "If an unsigned int is 2 bytes wide then, What will be the output of the program ?\r\n\r\n#include<stdio.h>\r\n\r\nint main()\r\n{\r\n    unsigned int a=0xffff;\r\n    ~a;\r\n    printf(\"%x\\n\", a);\r\n    return 0;\r\n}", correct_answer: "ffff"},
  {exam_id: 10, content: "Brass gets discoloured in air because of the presence of which of the following gases in air?\r\n", correct_answer: "Oxygen"},
  {exam_id: 10, content: "\t\r\nWhich of the following is a non metal that remains liquid at room temperature?", correct_answer: "Phosphorous"},
  {exam_id: 10, content: "Chlorophyll is a naturally occurring chelate compound in which central metal is", correct_answer: "copper"},
  {exam_id: 10, content: "Which of the following is used in pencils?\r\n", correct_answer: "Graphite"},
  {exam_id: 10, content: "Which of the following metals forms an amalgam with other metals?", correct_answer: "Tin"},
  {exam_id: 11, content: "What is the color code for a 220 omega.gif 5% resistor?", correct_answer: "Red"},
  {exam_id: 11, content: " If 60 J of energy are available for every 15 C of charge, what is the voltage?", correct_answer: "4"},
  {exam_id: 11, content: "An atom's atomic number is determined by the number of:", correct_answer: "neutron"},
  {exam_id: 11, content: " A voltage will influence current only if the circuit is:", correct_answer: "open"},
  {exam_id: 11, content: "Which resistive component is designed to be temperature sensitive?", correct_answer: "Potentiometer"},
  {exam_id: 12, content: "Grand Central Terminal, Park Avenue, New York is the world's", correct_answer: "largest railway station"},
  {exam_id: 12, content: "Entomology is the science that studies", correct_answer: "Behavior of human beings"},
  {exam_id: 12, content: "Eritrea, which became the 182nd member of the UN in 1993, is in the continent of", correct_answer: "Asia"},
  {exam_id: 12, content: "Garampani sanctuary is located at", correct_answer: "Junagarh, Gujarat"},
  {exam_id: 12, content: "Hitler party which came into power in 1933 is known as", correct_answer: "Labour Party"}
])
